#!/bin/sh
#
# airport-ssid: print the OSX Airport SSID, i.e. current Wi-Fi name.
#
# Example:
#
#     $ airport-ssid
#     My WiFi Network
#
# ## About ##
#
#   * Command: airport-ssid
#   * Version: 1.1.0
#   * Created: 2015-06-30
#   * Updated: 2016-02-09
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I |
sed -n 's/^ *SSID: //p'
