#!/bin/sh
#
# airport-ssid:
# show the current OS X Wi-Fi Airport SSID
#
# Example:
#
#     $ airport-ssid
#     Example Service Set Identifier
#
# Command: airport-ssid
# Version: 1.1.0
# Created: 2015-06-30
# Updated: 2016-02-09
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I |
sed -n 's/^ *SSID: //p'
